package in.marketbrain.training;

import org.junit.jupiter.api.Test;
import java.io.File;
import java.util.*;
import static org.assertj.core.api.Assertions.*;

/** Explicit offline probe, not selected by the default *Test suite. No application context or DB. */
class NumericalResearchExportEvidenceProbe {
    @Test void replaySuppliedSavedEvidence() throws Exception {
        var mapper=NumericalResearchExportTest.MAPPER;
        var featureBytes=java.nio.file.Files.readAllBytes(new File(System.getProperty("featureEvidence")).toPath());
        var outcomeBytes=java.nio.file.Files.readAllBytes(new File(System.getProperty("outcomeEvidence")).toPath());
        var sha=java.security.MessageDigest.getInstance("SHA-256");
        var featureHash=HexFormat.of().formatHex(sha.digest(featureBytes));
        var outcomeHash=HexFormat.of().formatHex(sha.digest(outcomeBytes));
        var feature=mapper.readTree(featureBytes);
        var outcome=mapper.readTree(outcomeBytes);
        assertThat(outcome.path("inputSha256").asText()).isEqualToIgnoringCase(featureHash);
        var payload=feature.path("snapshot").path("payload");
        var instruments=new ArrayList<NumericalResearchExport.Instrument>();int n=0;
        for(var item:payload.path("instruments")) {
            var bars=new ArrayList<NumericalResearchExport.Bar>();
            for(var b:item.path("canonicalBars"))bars.add(mapper.treeToValue(b,NumericalResearchExport.Bar.class));
            for(var b:outcome.path("outcome").path("instruments").get(n++).path("canonicalBars"))bars.add(mapper.treeToValue(b,NumericalResearchExport.Bar.class));
            instruments.add(new NumericalResearchExport.Instrument(item.path("instrumentId").asLong(),item.path("symbol").asText(),bars));
        }
        var input=new NumericalResearchExport.Input(UUID.fromString(payload.path("datasetRunId").asText()),payload.path("datasetManifestHash").asText(),
                featureHash,outcomeHash,NumericalResearchExportTest.sessions(),instruments);
        var result=new NumericalResearchExport().build(input);
        assertThat(result.candidateRowCount()).isEqualTo(152);assertThat(result.completeArithmeticRowCount()).isEqualTo(152);
        int compared=0;
        for(var item:payload.path("instruments"))for(var row:item.path("rows")) {
            var generated=result.rows().stream().filter(r->r.instrumentId()==item.path("instrumentId").asLong()
                    &&r.decisionDate().toString().equals(row.path("decisionDate").asText())).findFirst().orElseThrow();
            com.fasterxml.jackson.databind.JsonNode generatedValues=mapper.valueToTree(generated.featureSnapshot().features());
            assertThat(generatedValues.size()).isEqualTo(row.path("features").size());
            row.path("features").fields().forEachRemaining(field->assertThat(generatedValues.get(field.getKey()).decimalValue())
                    .isEqualByComparingTo(field.getValue().decimalValue()));compared++;
        }
        assertThat(compared).isEqualTo(12);
        // Test result only, not the full production evidence envelope generated by the collector.
        mapper.writeValue(new File("target/replayed-research-test-only.json"),result);
        System.out.println("SAVED EVIDENCE PROBE: 152/152 arithmetic rows, 12 original feature rows unchanged; training blocked.");
    }
}
